### ISSUE TITLE
Javascript: Sub deve retornar valor absoluto

### ISSUE THREAD

**Issue by levysantiago** [mate28-ic-ufba/bugs-sandbox#7]
https://github.com/mate28-ic-ufba/bugs-sandbox/blob/main/javascript/Calculator.js
Função `sub()` deve retornar o valor absoluto do resultado de `a - b`. Ou seja:

```
10 - 2 = 8
2 - 10 = 8
```
Sugestão: se `b > a` fazemos b - a, senão faz o contrário.
Ou se o resultado for negativo, multiplica por -1.

**Comment by Angelaps** [comment]
Vou ficar responsável por essa issue

**Comment by levysantiago** [comment]
Fechado em commit https://github.com/mate28-ic-ufba/bugs-sandbox/commit/bab4f1f89edfcc33aec9ca2dcd08b1d63af622b9
